2022-12-19 15:32:29,796 INFO    MainThread:3463615 [wandb_setup.py:_flush():69] setting env: {}
2022-12-19 15:32:29,796 INFO    MainThread:3463615 [wandb_setup.py:_flush():69] setting login settings: {}
2022-12-19 15:32:29,797 INFO    MainThread:3463615 [wandb_init.py:_log_setup():319] Logging user logs to /home/dmivilensky/Diffusion-LM/wandb/run-20221219_153229-refactoring1/logs/debug.log
2022-12-19 15:32:29,797 INFO    MainThread:3463615 [wandb_init.py:_log_setup():320] Logging internal logs to /home/dmivilensky/Diffusion-LM/wandb/run-20221219_153229-refactoring1/logs/debug-internal.log
2022-12-19 15:32:29,797 INFO    MainThread:3463615 [wandb_init.py:init():352] calling init triggers
2022-12-19 15:32:29,797 INFO    MainThread:3463615 [wandb_init.py:init():357] wandb.init called with sweep_config: {}
config: {}
2022-12-19 15:32:29,797 INFO    MainThread:3463615 [wandb_init.py:init():401] starting backend
2022-12-19 15:32:29,797 INFO    MainThread:3463615 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-12-19 15:32:29,864 INFO    MainThread:3463615 [backend.py:ensure_launched():123] starting backend process...
2022-12-19 15:32:29,924 INFO    MainThread:3463615 [backend.py:ensure_launched():127] started backend process with pid: 3471889
2022-12-19 15:32:29,926 INFO    MainThread:3463615 [wandb_init.py:init():406] backend started and connected
2022-12-19 15:32:29,928 INFO    MainThread:3463615 [wandb_init.py:init():446] updated telemetry
2022-12-19 15:32:29,929 INFO    MainThread:3463615 [wandb_init.py:init():465] communicating current version
2022-12-19 15:32:30,942 INFO    MainThread:3463615 [wandb_init.py:init():470] got version response upgrade_message: "wandb version 0.13.7 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-12-19 15:32:30,943 INFO    MainThread:3463615 [wandb_init.py:init():478] communicating run to backend with 30 second timeout
2022-12-19 15:32:31,228 INFO    MainThread:3463615 [wandb_init.py:init():503] starting run threads in backend
2022-12-19 15:32:31,534 INFO    MainThread:3463615 [wandb_run.py:_console_start():1422] atexit reg
2022-12-19 15:32:31,535 INFO    MainThread:3463615 [wandb_run.py:_redirect():1285] redirect: SettingsConsole.REDIRECT
2022-12-19 15:32:31,535 INFO    MainThread:3463615 [wandb_run.py:_redirect():1290] Redirecting console.
2022-12-19 15:32:31,535 INFO    MainThread:3463615 [redirect.py:install():213] install start
2022-12-19 15:32:31,536 INFO    MainThread:3463615 [redirect.py:install():228] install stop
2022-12-19 15:32:31,536 INFO    MainThread:3463615 [redirect.py:install():213] install start
2022-12-19 15:32:31,538 INFO    MainThread:3463615 [redirect.py:install():228] install stop
2022-12-19 15:32:31,538 INFO    MainThread:3463615 [wandb_run.py:_redirect():1336] Redirects installed.
2022-12-19 15:32:31,538 INFO    MainThread:3463615 [wandb_init.py:init():527] run started, returning control to user process
2022-12-19 15:33:35,833 INFO    MainThread:3463615 [wandb_run.py:_atexit_cleanup():1392] got exitcode: 1
2022-12-19 15:33:35,835 INFO    MainThread:3463615 [wandb_run.py:_restore():1364] restore
2022-12-19 15:33:35,836 INFO    MainThread:3463615 [redirect.py:uninstall():232] uninstall start
2022-12-19 15:33:35,836 INFO    MainThread:3463615 [redirect.py:_stop():287] _stop: stdout
2022-12-19 15:33:35,836 INFO    stdout    :3463615 [redirect.py:_pipe_relay():129] relay done saw last write: stdout
2022-12-19 15:33:35,836 INFO    stdout    :3463615 [redirect.py:_pipe_relay():145] relay done done: stdout
2022-12-19 15:33:35,836 INFO    MainThread:3463615 [redirect.py:_stop():293] _stop closed: stdout
2022-12-19 15:33:35,836 INFO    MainThread:3463615 [redirect.py:_stop():299] _stop joined: stdout
2022-12-19 15:33:35,836 INFO    MainThread:3463615 [redirect.py:_stop():301] _stop rd closed: stdout
2022-12-19 15:33:35,836 INFO    MainThread:3463615 [redirect.py:uninstall():236] uninstall done
2022-12-19 15:33:35,837 INFO    MainThread:3463615 [redirect.py:uninstall():232] uninstall start
2022-12-19 15:33:35,837 INFO    MainThread:3463615 [redirect.py:_stop():287] _stop: stderr
2022-12-19 15:33:35,837 INFO    stderr    :3463615 [redirect.py:_pipe_relay():129] relay done saw last write: stderr
2022-12-19 15:33:35,837 INFO    stderr    :3463615 [redirect.py:_pipe_relay():145] relay done done: stderr
2022-12-19 15:33:35,837 INFO    MainThread:3463615 [redirect.py:_stop():293] _stop closed: stderr
2022-12-19 15:33:35,837 INFO    MainThread:3463615 [redirect.py:_stop():299] _stop joined: stderr
2022-12-19 15:33:35,837 INFO    MainThread:3463615 [redirect.py:_stop():301] _stop rd closed: stderr
2022-12-19 15:33:35,837 INFO    MainThread:3463615 [redirect.py:uninstall():236] uninstall done
2022-12-19 15:33:39,768 ERROR   MainThread:3463615 [wandb_run.py:_atexit_cleanup():1410] Problem finishing run
Traceback (most recent call last):
  File "/home/dmivilensky/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1400, in _atexit_cleanup
    self._on_finish()
  File "/home/dmivilensky/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1537, in _on_finish
    self.history._flush()
  File "/home/dmivilensky/.local/lib/python3.8/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/home/dmivilensky/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 732, in _history_callback
    self._backend.interface.publish_history(
  File "/home/dmivilensky/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 220, in publish_history
    item.value_json = json_dumps_safer_history(v)  # type: ignore
  File "/home/dmivilensky/.local/lib/python3.8/site-packages/wandb/util.py", line 610, in json_dumps_safer_history
    return json.dumps(obj, cls=WandBHistoryJSONEncoder, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/dmivilensky/.local/lib/python3.8/site-packages/wandb/util.py", line 573, in default
    obj, converted = json_friendly(obj)
  File "/home/dmivilensky/.local/lib/python3.8/site-packages/wandb/util.py", line 426, in json_friendly
    obj = obj.numpy()
TypeError: can't convert cuda:3 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
